import type { FormData } from '../components/admin/FormEditor';

export const DEFAULT_FORMS: FormData[] = [
    {
        id: 'form_1',
        title: 'Default Credentials Form',
        author: 'admin',
        date: '2025-10-28T19:05:00Z',
        deliveryPreset: 'all',
        deliveryOptions: ['email', 'whatsapp', 'slack'],
        schedules: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
        times: ['09:00', '12:00', '15:00'],
        webhookUrl: '',
        lockAdsFields: false,
    },
    {
        id: 'form_1761678397',
        title: 'Basic Plan',
        author: 'Wedosome',
        date: '2026-03-08T16:49:00Z',
        deliveryPreset: 'slack_email',
        deliveryOptions: ['email', 'slack'],
        schedules: ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
        times: ['09:00'],
        webhookUrl: '',
        lockAdsFields: false,
    },
    {
        id: 'form_1761678397_copy_1766094934',
        title: 'Standard Plan',
        author: 'Wedosome',
        date: '2026-02-06T21:53:00Z',
        deliveryPreset: 'slack_whatsapp',
        deliveryOptions: ['whatsapp', 'slack'],
        schedules: ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
        times: ['09:00'],
        webhookUrl: '',
        lockAdsFields: false,
    },
    {
        id: 'form_1761678397_c',
        title: 'Premium Plan',
        author: 'Wedosome',
        date: '2026-01-08T16:53:00Z',
        deliveryPreset: 'all',
        deliveryOptions: ['email', 'whatsapp', 'slack'],
        schedules: ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
        times: ['09:00', '15:00'],
        webhookUrl: '',
        lockAdsFields: false,
    },
];
